version: 0.2
phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/cfn/lambda/drs-plan-automation-api/src
      - npm install
      - cd ..
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --s3-bucket ${drs_s3_bucket_name} --s3-prefix "sam-deployments/drs-plan-automation-lambda-api" --capabilities "CAPABILITY_NAMED_IAM" --stack-name "drs-plan-automation-lambda-api"

